### ISSUE TITLE
Serverless: Failure: item.once is not a function

### ISSUE THREAD

**Issue by Botre** [dougmoscrop/serverless-http#85]
Getting this on every invocation since I updated to 1.10.

Reverting to 1.9.1 fixes the issue for me.

I'm using Koa & serverless-offline, can be repro'd with the following:

```javascripts
const serverless = require("serverless-http");
const Koa = require("koa");
const application = new Koa();
module.exports.handler = serverless(application);
```

**Comment by jmannau** [comment]
I experienced the same error and have tracked it down to the difference between koa v1 & v2.  I have created a branch and updated this project to test against koa v2  (https://github.com/jmannau/serverless-http/tree/koa-v2). This problem is now reproducible. I hope this helps.

**Comment by jmannau** [comment]
ok, I don't know if this helps, in [get-handler.js line#23](/master/lib/get-handler.js#L23) koa returns `true` in responseOverride in certain conditions. When it does this, the responseOverride (being `true` is returned from the promise. Not the response itself. This causes the downstream error. It may be prudent to add a check that the `responseOverride` is valid `response` object before continuing.

**Comment by dougmoscrop** [comment]
Yes thank youm I'll fix it this morning!

**Comment by dougmoscrop** [comment]
Fixed in 1.10.1

**Comment by Botre** [comment]
All good!
